version: '3.5'

services:
  db_hackprod_auth:
    container_name: db_hackprod_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:15.3
#    command:
#      - "postgres"
#      - "-c"
#      - "port=6101"
#    volumes:
#      - db_hackprod_auth:/var/lib/postgresql/data/
#    networks:
#      - internal_net